"""Build a voice comparison page for ALL eligible voice samples.

Scans ~/Music/voice-analysis/ for *.wav files, processes each through
synth_pure, and emits a single HTML page with a dropdown to switch between
them. Audio + PNGs are written next to each input.

Usable inputs are auto-detected by:
  - peak > 0.1 (skip empty / near-silent files)
  - duration > 0.5s (skip very short noise blips)

Usage:
    python tools/build_voice_compare_v3.py
    python tools/build_voice_compare_v3.py path/to/specific.wav [...]
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import logging
import sys
import wave
from pathlib import Path

import librosa
import librosa.display
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import soundfile as sf

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tools.synth_pure import synthesize as synth_render
from tools.synth_pure import analyze as synth_analyze

log = logging.getLogger("build_voice_compare_v3")

VOICE_DIR = Path.home() / "Music" / "voice-analysis"
OUT_DIR = VOICE_DIR / "viz"
OUT_DIR.mkdir(parents=True, exist_ok=True)
HTML_PATH = OUT_DIR / "index.html"

# synth parameters — match what worked for nico_voz_sample_02
SYNTH_PARAMS = dict(
    thresh_db=-30.0,
    f0_min=70.0,
    f0_max=400.0,
    max_voices=6,
    noise_floor_db=-40.0,
    gain_curve="sqrt",
)

# Detection: which channel of a stereo file actually has audio?
def pick_mono_channel(y: np.ndarray) -> np.ndarray:
    if y.ndim == 1:
        return y
    # If one channel is empty, use the other; otherwise average.
    mag_l = float(np.abs(y[:, 0]).max())
    mag_r = float(np.abs(y[:, 1]).max())
    if mag_r > mag_l * 5:
        return y[:, 1]
    if mag_l > mag_r * 5:
        return y[:, 0]
    return y.mean(axis=1)


def is_usable(path: Path) -> tuple[bool, str]:
    """Return (usable, reason) for a candidate input WAV."""
    try:
        y, sr = sf.read(str(path))
    except Exception as exc:
        return False, f"read error: {exc}"
    y = pick_mono_channel(np.asarray(y, dtype=np.float32))
    if y.size == 0:
        return False, "empty"
    peak = float(np.abs(y).max())
    rms = float(np.sqrt(np.mean(y ** 2)))
    dur = len(y) / sr
    if dur < 0.5:
        return False, f"too short ({dur:.2f}s)"
    if peak < 0.1:
        return False, f"peak too low ({peak:.3f})"
    if rms < 0.01:
        return False, f"RMS too low ({rms:.3f})"
    return True, f"{dur:.2f}s @ {sr} Hz, peak={peak:.2f}, RMS={rms:.3f}"


SKIP_SUFFIXES = ("_synth", "_orig", "_mono", "_clean", "_filt", "_0-9s", "_side_by_side")


def discover_inputs(voice_dir: Path) -> list[Path]:
    """Find usable voice samples in voice_dir.

    Auto-skips obvious derivative files by suffix so we only process the
    original recordings. Suffixes like '_synth', '_mono', '_clean' are
    generated by our pipeline or earlier sessions — not original inputs.
    """
    candidates = sorted(voice_dir.glob("*.wav"))
    out = []
    skipped = []
    for c in candidates:
        stem = c.stem
        if any(stem.endswith(suf) for suf in SKIP_SUFFIXES):
            skipped.append((c, f"derivative (suffix {stem[len(stem)-6:]})"))
            continue
        ok, reason = is_usable(c)
        if ok:
            out.append(c)
        else:
            skipped.append((c, reason))
    log.info("Discovered %d usable voice samples (skipped %d derivatives/empty):",
             len(out), len(skipped))
    for path, reason in skipped:
        log.info("  SKIP %s: %s", path.name, reason)
    return out


def process_one(input_path: Path) -> dict:
    """Process one voice sample: synthesize + spectrograms + audio b64."""
    log.info("=" * 60)
    log.info("Processing: %s", input_path.name)

    # 1. Load + (stereo → mono if needed) + resample to 44.1kHz
    y, sr = sf.read(str(input_path))
    y = pick_mono_channel(np.asarray(y, dtype=np.float32))
    sr_target = 44100
    if sr != sr_target:
        y = librosa.resample(y, orig_sr=sr, target_sr=sr_target)
        sr = sr_target
    log.info("  loaded: %.2fs @ %d Hz, peak=%.3f, RMS=%.3f",
             len(y) / sr, sr, float(np.abs(y).max()),
             float(np.sqrt(np.mean(y ** 2))))

    # 2. Synthesize via synth_pure
    log.info("  synthesizing...")
    out_mono = synth_render(y, sr, **SYNTH_PARAMS)
    log.info("  synth raw: peak=%.3f, RMS=%.3f",
             float(np.abs(out_mono).max()),
             float(np.sqrt(np.mean(out_mono ** 2))))

    # 3. RMS-balance synth to 0.7× orig
    orig_rms = float(np.sqrt(np.mean(y ** 2)))
    synth_rms = float(np.sqrt(np.mean(out_mono ** 2)))
    target_rms = orig_rms * 0.7
    if synth_rms > 0:
        g = target_rms / synth_rms
        out_mono = out_mono * g
    out_mono = np.tanh(out_mono) / np.tanh(1.0) * 0.95
    log.info("  synth balanced: peak=%.3f, RMS=%.3f (target=%.3f)",
             float(np.abs(out_mono).max()),
             float(np.sqrt(np.mean(out_mono ** 2))), target_rms)

    # 4. Save stereo WAVs
    base = input_path.stem
    orig_path = OUT_DIR / f"{base}_orig.wav"
    synth_path = OUT_DIR / f"{base}_synth.wav"
    for wav_path, sig in [(orig_path, y), (synth_path, out_mono)]:
        stereo = np.column_stack([sig, sig])
        pcm = (np.clip(stereo, -1.0, 1.0) * 32767).astype(np.int16)
        with wave.open(str(wav_path), "wb") as w:
            w.setnchannels(2)
            w.setsampwidth(2)
            w.setframerate(sr)
            w.writeframes(pcm.tobytes())

    # 5. PNGs
    png_paths = make_pngs(y, out_mono, sr, base)

    # 6. Compute F0 + stats
    times, f0, voiced, _ = synth_analyze(y, sr,
                                          SYNTH_PARAMS["f0_min"],
                                          SYNTH_PARAMS["f0_max"])
    f0v = f0[voiced]
    stats = {
        "voiced_frames": int(voiced.sum()),
        "total_frames": int(len(voiced)),
        "duration": round(len(y) / sr, 3),
        "sample_rate": sr,
        "f0_min": round(float(f0v.min()), 1) if len(f0v) else 0,
        "f0_max": round(float(f0v.max()), 1) if len(f0v) else 0,
        "f0_mean": round(float(f0v.mean()), 1) if len(f0v) else 0,
        "f0_times": times.tolist(),
        "f0_values": [float(v) if voiced[i] else 0.0
                      for i, v in enumerate(f0)],
        "f0_voiced": [bool(v) for v in voiced],
    }

    return {
        "id": base,
        "label": base.replace("_", " "),
        "src_path": str(input_path),
        "stats": stats,
        "files": {
            "orig_wav": f"{base}_orig.wav",
            "synth_wav": f"{base}_synth.wav",
            "side_by_side": f"{base}_side_by_side.png",
            "overlay_orig_f0": f"{base}_overlay_orig_f0.png",
            "overlay_synth_f0": f"{base}_overlay_synth_f0.png",
        },
    }


def make_pngs(y_orig, y_synth, sr, base) -> dict:
    """Render the 3 PNG spectrograms for a sample."""
    n_fft = 2048
    hop = 512

    S_orig = np.abs(librosa.stft(y_orig, n_fft=n_fft, hop_length=hop))
    S_synth = np.abs(librosa.stft(y_synth, n_fft=n_fft, hop_length=hop))
    S_orig_db = librosa.amplitude_to_db(S_orig, ref=np.max(S_orig))
    S_synth_db = librosa.amplitude_to_db(S_synth, ref=np.max(S_synth))

    def plot_spec(ax, S_db, title, cmap):
        img = librosa.display.specshow(
            S_db, sr=sr, hop_length=hop,
            x_axis="time", y_axis="hz", cmap=cmap, ax=ax,
        )
        ax.set_ylim(0, 800)
        ax.set_title(title, color="white", fontsize=12)
        ax.set_ylabel("Hz", color="#aaa")
        ax.tick_params(colors="#888", labelsize=9)
        ax.set_xlabel("Time (s)", color="#aaa")
        return img

    # Side-by-side
    fig, axes = plt.subplots(2, 1, figsize=(20, 10), sharex=True,
                              facecolor="#0e1116")
    img_o = plot_spec(axes[0], S_orig_db, "Original voice", "magma")
    img_s = plot_spec(axes[1], S_synth_db, "Shaper synthesis (additive sines)", "viridis")
    for ax in axes:
        ax.set_facecolor("#000")
    fig.colorbar(img_o, ax=axes[0], format="%+2.0f dB", label="dB")
    fig.colorbar(img_s, ax=axes[1], format="%+2.0f dB", label="dB")
    plt.tight_layout()
    side_by_side = OUT_DIR / f"{base}_side_by_side.png"
    plt.savefig(side_by_side, dpi=200, facecolor=fig.get_facecolor())
    plt.close()

    # F0 analysis (we already have it via analyze; redo here for plotting)
    times_p, f0_p, voiced_p, _ = synth_analyze(
        y_orig, sr, SYNTH_PARAMS["f0_min"], SYNTH_PARAMS["f0_max"]
    )
    times_synth = librosa.frames_to_time(np.arange(S_synth.shape[1]),
                                         sr=sr, hop_length=hop)
    f0_on_synth = np.interp(times_synth, times_p, f0_p, left=0, right=0)
    voiced_on_synth = np.interp(times_synth, times_p, voiced_p.astype(float),
                                left=0, right=0) > 0.5
    f0_plot = np.where(voiced_on_synth, f0_on_synth, np.nan)

    # Synth + F0
    fig, ax = plt.subplots(figsize=(20, 6), facecolor="#0e1116")
    img = librosa.display.specshow(
        S_synth_db, sr=sr, hop_length=hop,
        x_axis="time", y_axis="hz", cmap="magma", ax=ax,
    )
    ax.set_ylim(0, 800)
    ax.set_facecolor("#000")
    ax.plot(times_synth, f0_plot, color="#00ffd0", lw=2.0, label="F0 (pYIN)")
    ax.set_title("Shaper synthesis + F0 trajectory", color="white", fontsize=12)
    ax.set_ylabel("Hz", color="#aaa")
    ax.set_xlabel("Time (s)", color="#aaa")
    ax.tick_params(colors="#888", labelsize=9)
    ax.legend(loc="upper right", facecolor="#161b22", edgecolor="#444",
              labelcolor="white")
    fig.colorbar(img, ax=ax, format="%+2.0f dB", label="dB")
    plt.tight_layout()
    overlay_synth = OUT_DIR / f"{base}_overlay_synth_f0.png"
    plt.savefig(overlay_synth, dpi=200, facecolor=fig.get_facecolor())
    plt.close()

    # Original + F0
    fig, ax = plt.subplots(figsize=(20, 6), facecolor="#0e1116")
    img = librosa.display.specshow(
        S_orig_db, sr=sr, hop_length=hop,
        x_axis="time", y_axis="hz", cmap="magma", ax=ax,
    )
    ax.set_ylim(0, 800)
    ax.set_facecolor("#000")
    ax.plot(times_synth, f0_plot, color="#00ffd0", lw=2.0, label="F0 (pYIN)")
    ax.set_title("Original voice + F0 trajectory", color="white", fontsize=12)
    ax.set_ylabel("Hz", color="#aaa")
    ax.set_xlabel("Time (s)", color="#aaa")
    ax.tick_params(colors="#888", labelsize=9)
    ax.legend(loc="upper right", facecolor="#161b22", edgecolor="#444",
              labelcolor="white")
    fig.colorbar(img, ax=ax, format="%+2.0f dB", label="dB")
    plt.tight_layout()
    overlay_orig = OUT_DIR / f"{base}_overlay_orig_f0.png"
    plt.savefig(overlay_orig, dpi=200, facecolor=fig.get_facecolor())
    plt.close()

    return {
        "side_by_side": side_by_side.name,
        "overlay_synth": overlay_synth.name,
        "overlay_orig": overlay_orig.name,
    }


def build_html(samples: list[dict]) -> str:
    """Render the comparison HTML with a dropdown selector."""
    samples_json = json.dumps(samples)
    options = "\n".join(
        f'      <option value="{s["id"]}">{s["label"]} '
        f'({s["stats"]["duration"]:.2f}s, F0 {s["stats"]["f0_mean"]:.0f}Hz)</option>'
        for s in samples
    )
    # Stats panel content (one block per sample; hidden/shown via JS)
    stats_blocks = "\n".join(
        f'<div class="stats-block" data-id="{s["id"]}">\n'
        f'  <div class="stat"><div class="l">Voiced frames</div>'
        f'<div class="v">{s["stats"]["voiced_frames"]} / {s["stats"]["total_frames"]}</div></div>\n'
        f'  <div class="stat"><div class="l">F0 mean</div>'
        f'<div class="v">{s["stats"]["f0_mean"]} Hz</div></div>\n'
        f'  <div class="stat"><div class="l">F0 range</div>'
        f'<div class="v">{s["stats"]["f0_min"]}–{s["stats"]["f0_max"]} Hz</div></div>\n'
        f'  <div class="stat"><div class="l">Duration</div>'
        f'<div class="v">{s["stats"]["duration"]:.2f} s</div></div>\n'
        f'</div>'
        for s in samples
    )
    # Image blocks (one per sample; shown when selected)
    img_blocks = "\n".join(
        f'<div class="sample-panel" data-id="{s["id"]}" style="display:none">\n'
        f'  <h2>Side by side</h2>\n'
        f'  <div class="panel"><img src="{s["files"]["side_by_side"]}" alt="side-by-side"></div>\n'
        f'  <div class="audio-row">\n'
        f'    <div>\n'
        f'      <div class="audio-label">Original</div>\n'
        f'      <audio controls preload="metadata" src="{s["files"]["orig_wav"]}"></audio>\n'
        f'    </div>\n'
        f'    <div>\n'
        f'      <div class="audio-label">Shaper synthesis</div>\n'
        f'      <audio controls preload="metadata" src="{s["files"]["synth_wav"]}"></audio>\n'
        f'    </div>\n'
        f'  </div>\n'
        f'  <h2>Synthesized + F0 trajectory</h2>\n'
        f'  <div class="panel"><img src="{s["files"]["overlay_synth_f0"]}" alt="synth + F0"></div>\n'
        f'  <h2>Original + F0 trajectory</h2>\n'
        f'  <div class="panel"><img src="{s["files"]["overlay_orig_f0"]}" alt="original + F0"></div>\n'
        f'</div>'
        for s in samples
    )
    first_id = samples[0]["id"] if samples else ""

    return f"""<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>Voice → Shaper comparison</title>
<style>
  body {{
    margin: 0; padding: 24px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    background: #0e1116; color: #c9d1d9;
  }}
  h1 {{ margin: 0 0 8px; font-size: 20px; }}
  h2 {{ margin: 24px 0 8px; font-size: 13px;
        color: #8b949e; text-transform: uppercase; letter-spacing: 0.05em; }}
  .sub {{ color: #8b949e; font-size: 13px; margin-bottom: 16px; max-width: 900px; }}
  .panel {{ background: #161b22; border: 1px solid #30363d;
            border-radius: 8px; padding: 16px; margin-bottom: 16px; }}
  img {{ display: block; max-width: 100%; height: auto;
         border-radius: 4px; }}
  audio {{ width: 100%; margin-top: 8px; }}
  .audio-row {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px;
                 margin-top: 8px; }}
  .audio-label {{ font-size: 12px; color: #58a6ff; margin-bottom: 4px;
                  font-weight: 600; }}
  .stats {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px;
            margin-bottom: 16px; }}
  .stats-block {{ display: none; }}
  .stats-block.active {{ display: grid; }}
  .stat {{ background: #161b22; padding: 12px; border-radius: 6px;
           border: 1px solid #21262d; }}
  .stat .v {{ font-size: 22px; font-weight: 600; color: #58a6ff; }}
  .stat .l {{ font-size: 11px; color: #8b949e;
              text-transform: uppercase; letter-spacing: 0.05em; }}
  .selector {{
    background: #161b22; border: 1px solid #30363d; border-radius: 8px;
    padding: 12px 16px; margin-bottom: 16px;
    display: flex; align-items: center; gap: 12px;
  }}
  .selector label {{ font-size: 13px; color: #8b949e; font-weight: 600; }}
  .selector select {{
    flex: 1; max-width: 600px; padding: 8px 12px;
    background: #0e1116; color: #c9d1d9; border: 1px solid #30363d;
    border-radius: 6px; font-size: 14px; font-family: inherit;
  }}
  .sample-panel {{ display: none; }}
  .sample-panel.active {{ display: block; }}
  .legend {{ color: #8b949e; font-size: 12px; margin-top: 4px; }}
  .upload-note {{
    background: #1c2128; border-left: 3px solid #58a6ff;
    padding: 10px 14px; margin-bottom: 16px;
    color: #8b949e; font-size: 12px;
  }}
</style>
</head>
<body>
  <h1>Voice → Shaper comparison</h1>
  <div class="sub">
    Each voice sample below is analyzed with librosa.pyin (F0) and STFT
    magnitude at f<sub>1</sub>·N, then re-rendered as 6 pure sine harmonics in
    the natural harmonic series. Spectrograms use STFT n_fft=2048, zoomed to
    0-800 Hz. Synth passes through a Butterworth low-pass filter
    (cutoff ≈ max_harmonic × max_F0 × 1.1 Hz) to kill intermodulation products.
  </div>

  <div class="upload-note">
    Audio drop / upload coming soon — currently this list is built by
    scanning <code>~/Music/voice-analysis/*.wav</code> on each build.
  </div>

  <div class="selector">
    <label for="sample-select">Voice sample:</label>
    <select id="sample-select">{options}
    </select>
    <span id="sample-count" class="legend">{len(samples)} samples</span>
  </div>

  <div id="stats-container">{stats_blocks}
  </div>

  {img_blocks}

  <script>
  const SAMPLES = {samples_json};
  const select = document.getElementById('sample-select');
  function activate(id) {{
    // Stats blocks
    document.querySelectorAll('.stats-block').forEach(el => {{
      el.classList.toggle('active', el.dataset.id === id);
    }});
    // Sample panels
    document.querySelectorAll('.sample-panel').forEach(el => {{
      el.classList.toggle('active', el.dataset.id === id);
    }});
    // Pause all other audios
    document.querySelectorAll('audio').forEach(a => {{
      if (!a.closest('.sample-panel.active')) a.pause();
    }});
    // Update URL hash so reload preserves selection
    history.replaceState(null, '', '#' + id);
  }}
  select.addEventListener('change', (e) => activate(e.target.value));
  // Initial: pick from hash or first
  const initial = location.hash.slice(1) || '{first_id}';
  if (Array.from(select.options).some(o => o.value === initial)) {{
    select.value = initial;
  }}
  activate(select.value);
  </script>
</body>
</html>
"""


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inputs", nargs="*", type=Path,
                        help="Specific WAV files (default: scan voice dir)")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%H:%M:%S",
    )

    if args.inputs:
        inputs = args.inputs
        log.info("Using %d specified inputs", len(inputs))
    else:
        inputs = discover_inputs(VOICE_DIR)
    if not inputs:
        log.error("No usable voice samples found in %s", VOICE_DIR)
        sys.exit(1)

    samples = [process_one(p) for p in inputs]
    log.info("=" * 60)
    log.info("Processed %d samples", len(samples))

    html = build_html(samples)
    HTML_PATH.write_text(html)
    log.info("Wrote %s (%d KB)", HTML_PATH, HTML_PATH.stat().st_size // 1024)

    # Drop a manifest JSON alongside for debugging
    manifest = OUT_DIR / "manifest.json"
    manifest.write_text(json.dumps(samples, indent=2))
    log.info("Wrote %s", manifest)


if __name__ == "__main__":
    sys.exit(main())